//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoSite.Templates.Pages {
    
    
    public partial class NewsListPage {
        
        /// <summary>
        /// Breadcrumbs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DemoSite.Templates.Units.Breadcrumbs Breadcrumbs1;
        
        /// <summary>
        /// NewsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KalikoCMS.WebForms.WebControls.PageList NewsList;
        
        /// <summary>
        /// NewsPager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KalikoCMS.WebForms.WebControls.Pager NewsPager;
        
        /// <summary>
        /// YearList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KalikoCMS.WebForms.WebControls.MenuList YearList;
    }
}
