//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoSite.Templates.Units {
    
    
    public partial class Breadcrumbs {
        
        /// <summary>
        /// Breadcrumbs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KalikoCMS.WebForms.WebControls.Breadcrumbs Breadcrumbs1;
    }
}
